### ISSUE TITLE
Linking error when using the head of Master branch

### ISSUE THREAD

**Issue by yanggehua** [vxl/vxl#107]
I encountered the following linking error with MSVC 2015.  It is missing instantiation file for vnl_sym_matrix< vcl_complex<float> >, as needed by commit c68bf93aecaf79ebfa986dd394c7869016534d7a.  

10>test_complexify.obj : error LNK2019: unresolved external symbol "public: class vnl_sym_matrix<class std::complex<float> > & __cdecl vnl_sym_matrix<class std::complex<float> >::update(class vnl_sym_matrix<class std::complex<float> > const &,unsigned int)" (?update@?$vnl_sym_matrix@V?$complex@M@std@@@@QEAAAEAV1@AEBV1@I@Z) referenced in function "public: __cdecl vnl_sym_matrix<class std::complex<float> >::vnl_sym_matrix<class std::complex<float> >(class vnl_sym_matrix<class std::complex<float> > const &)" (??0?$vnl_sym_matrix@V?$complex@M@std@@@@QEAA@AEBV0@@Z)
10>D:\Code\vxl\bin-vc14-x64\core\vnl\tests\Debug\vnl_test_all.exe : fatal error LNK1120: 1 unresolved externals

**Comment by DVigneault** [comment]
@yanggehua Adding the instantiation now--sorry for adding a bug.  Does this need to be done for `vnl_diag_matrix` also?  Which files are you including to get the error?

**Comment by dstoup** [comment]
I believe this issue is resolved with merged branch.
