### ISSUE TITLE
EXPORT_LIBRARY_DEPENDENCIES needs to be modernized.

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#127]
This pull request is incomplete and should not be merged.
https://github.com/vxl/vxl/pull/122

Matt McCormic provide the following comment hints:
Thanks for looking at this. This is very old CMake usage that really should be updated. This patch looks good for removing the old code. However, more code is needed to replace its functionality. Using install(EXPORT and export( commands, a VXLTargets.cmake file can be created that replaces the old functionality.

I don't have the time to take that on. If you are willing and able, this page:

https://cmake.org/cmake/help/v3.4/manual/cmake-packages.7.html

explains the context a bit.

Otherwise, I think we should just set the policy to OLD to silence the warning along with at comment an an issue opened that explains what needs to be done.

From ITK's perspective, I don't think this is used, unless perhaps ITK_USE_SYSTEM_VXL is ON.

**Comment by thewtex** [comment]
@hjmjohnson FYI @ricortiz is looking into this.

**Comment by hjmjohnson** [comment]
I pushed a set of patches as another first step in this process.

Hans

**Comment by ricortiz** [comment]
Are those set of patches part of #184 pull request?
