### ISSUE TITLE
Windows MFC CMP0054 policy.

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#166]
CMake Warning (dev) at c:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindMFC.cmake:39 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MFC_HAVE_MFC" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  contrib/brl/bbas/bwm/CMakeLists.txt:100 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at c:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindMFC.cmake:39 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MFC_HAVE_MFC" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  config/cmake/Modules/NewCMake/FindECW.cmake:53 (find_package)
  contrib/brl/bbas/bwm/algo/CMakeLists.txt:30 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Could NOT find wxWidgets (missing:  wxWidgets_FOUND) 
-- Found JNI: C:/Program Files/Java/jdk1.7.0_79/lib/jawt.lib  
-- Could NOT find EXPAT (missing:  EXPAT_LIBRARY EXPAT_INCLUDE_DIR) 
-- Could NOT find EXPAT (missing:  EXPAT_LIBRARY EXPAT_INCLUDE_DIR) 
CMake Warning (dev) at c:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindMFC.cmake:39 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MFC_HAVE_MFC" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  config/cmake/Modules/NewCMake/FindECW.cmake:53 (find_package)
  contrib/brl/bseg/segv/CMakeLists.txt:16 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at c:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindMFC.cmake:39 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MFC_HAVE_MFC" will no longer be dereferenced when
  the policy is set to NEW.  Since the policy is not set the OLD behavior
  will be used.
Call Stack (most recent call first):
  config/cmake/Modules/NewCMake/FindECW.cmake:53 (find_package)
  contrib/brl/bseg/sbin/CMakeLists.txt:42 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by billhoffman** [comment]
This was fixed in CMake:
commit dcf298008f60fa00ddcb225b7a474317ad4d317f
Author: Brad King <brad.king@kitware.com>
Date:   Thu Mar 26 09:00:32 2015 -0400

    FindMFC: Use if(DEFINED) to simplify condition (#15477)
    
    Replace an old hack of the form 'if("${VAR}" MATCHES "^${VAR}$")'
    with the much simpler 'if(NOT DEFINED ${VAR})'.  This was exposed
    by a CMP0054 warning.

**Comment by hjmjohnson** [comment]
@billhoffman  Perhaps we can remove the local FindMFC.cmake from vxl then.

**Comment by billhoffman** [comment]
But the error you showing seems to be coming from CMake itself:  c:/Program Files (x86)/CMake/share/cmake-3.2/Modules/FindMFC.cmake:39 (if):

**Comment by hjmjohnson** [comment]
Minimum cmake version is now 3.3.0, so this is no longer an issue.
