### ISSUE TITLE
Default output library path not working

### ISSUE THREAD

**Issue by yidongVSI** [vxl/vxl#171]
In recent commit '3223fb2', old EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH were replaced by new CMAKE_LIBRARY_OUTPUT_DIRECTORY, CMAKE_ARCHIVE_OUTPUT_DIRECTORY and CMAKE_RUNTIME_OUTPUT_DIRECTORY.

EXECUTABLE_OUTPUT_PATH and LIBRARY_OUTPUT_PATH enable user to specify appropriate paths during configuration to store all built executable and static libraries, e.g., ${vxl_BINARY_DIR}/exe and ${vxl_BINARY_DIR}/lib.

In current configuration, CMAKE_LIBRARY_OUTPUT_DIRECTORY is ${vxl_BINARY_DIR}/lib by default, same as previous LIBRARY_OUTPUT_PATH.  But this default setting doesn't not work and there is no option for user to specify the executable_output_path.  
All the built library files and executables are in their individual location.  For example, compiled vgl lib is in ${vxl_BINARY_DIR}/core/vgl/libvgl.a and compiled vgl_test executable is in ${vxl_BINARY_DIR}/core/vgl/tests/vgl_test_all

**Comment by thewtex** [comment]
@yidongVSI  did you try setting CMAKE_LIBRARY_OUTPUT_DIRECTORY to be the path required?

**Comment by yidongVSI** [comment]
@thewtex Yes, I tried.  Neither the default value, ${vxl_BINARY_DIR}/lib, nor any specified path worked.

**Comment by hjmjohnson** [comment]
@yidongVSI I think I fixed this with the recent merge.  Please let me know if the problem is now resolved.
