### ISSUE TITLE
Transitive linking failure

### ISSUE THREAD

**Issue by TimCootes** [vxl/vxl#182]
Recent changes to VXL seem to have made transitive linking fail for libraries depending on VXL.

For instance, the following program requires vgl:

#include <vgl/vgl_vector_2d.h>
int main()
{
  vgl_vector_2d<double> vec(3,5);
  double L=vec.length();
}

If the CMakeLists.txt is:
---------------------------------------------
PROJECT(test_link_lib_project)

INCLUDE_DIRECTORIES(${VXL_CORE_INCLUDE_DIR})
INCLUDE_DIRECTORIES(${VXL_MUL_INCLUDE_DIR})

ADD_EXECUTABLE(test_prog test_prog.cxx)
TARGET_LINK_LIBRARIES(test_prog mbl)
-----------------------------------------------
one would expect the linking to work, since mbl depends on vgl, so vgl should be included.

Unfortunately this doesn't happen (when using Shared Libraries on Ubuntu with cmake 2.8.12.2 and gcc).
Instead I get the error:
undefined reference to `vgl_vector_2d<double>::length() const'

This is fixed if I modify the target_link_library list to:

TARGET_LINK_LIBRARIES(test_prog mbl ${VXL_LIB_PREFIX}vgl)

However, I shouldn't have to do that.
Any ideas?

**Comment by hjmjohnson** [comment]
This is related to #127.

It seems that a gradual change to update VXL for exporting of libraries is not going to work.

@TimCootes It is likely that I will need the weekend to resolve this issue.

pull request #183 is the first step towards making the conversion.
