### ISSUE TITLE
CMake fails

### ISSUE THREAD

**Issue by TimCootes** [vxl/vxl#192]
Unfortunately I can no longer build VXL at all (Ubuntu, cmake version 2.8.12.2)
When running configuring a fresh object directory using cmake ../vxl I get many errors of the form:

CMake Error: install(EXPORT "VXLTargets") given absolute DESTINATION "/usr/local/share/vxl/cmake" but the export references an installation of target "vcl" which has relative DESTINATION "lib".

**Comment by hjmjohnson** [comment]
I’ll continue looking into this asap.


--

**Comment by TimCootes** [comment]
The recent fix has made this error go away - thanks.

**Comment by hjmjohnson** [comment]
@TimCootes Hopefully this will become stable soon.  We have also improved the testing environment.

Thank you for your assistance and the example that you provided.
