### ISSUE TITLE
PR #184 broke compatibility with cmake 2.8.9

### ISSUE THREAD

**Issue by andyneff** [vxl/vxl#198]
I am running cmake 2.8.11 on CentOS 7, and can no longer get cmake to make vxl.

EXPORT_LINK_INTERFACE_LIBRARIES from [here](https://github.com/vxl/vxl/blob/master/config/cmake/export/VXLCreateProject.cmake#L29) does not appear to be supported until cmake 2.8.12

This is a significantly troublesome version threshold, since the entire RHEL/CentOS 7 community does not have access to Cmake pass 2.8.11

@ricortiz 
@hjmjohnson

**Comment by hjmjohnson** [comment]
@andyneff  We recentcly changed the travis build system to use 2.8.9 so that in the future these problems will be caught earlier.

https://github.com/vxl/vxl/blob/db1ab102c9b6d4f4e27d6d8c762e4c9e29c1c77c/.travis/install-deps.sh#L14

I'm working on a potential fix right now.

**Comment by hjmjohnson** [comment]
@andyneff Would you be able to test the proposed fix?

**Comment by hjmjohnson** [comment]
@andyneff I think this is fixed now.

**Comment by andyneff** [comment]
This fixed the Export problem, Thanks!

But I'm not 100% sure its working "right"? Now I have a new one...

This one I can't identify as easily, but we do know that I don't see this problem in CMake 2.8.12, but I do see these message in in CMake 2.8.11

Configuration finishes successfully, but during generation, I get about 197 messages. Here are the first 5

```
-- Configuring done
CMake Error in vcl/CMakeLists.txt:
  Target "vcl" INTERFACE_INCLUDE_DIRECTORIES property contains relative path:

    "include/vxl/vcl"


CMake Error in v3p/netlib/CMakeLists.txt:
  Target "netlib" INTERFACE_INCLUDE_DIRECTORIES property contains relative
  path:

    "include/vxl/v3p/netlib"


CMake Error in v3p/netlib/CMakeLists.txt:
  Target "v3p_netlib" INTERFACE_INCLUDE_DIRECTORIES property contains
  relative path:

    "include/vxl/v3p/netlib"


CMake Error in v3p/clipper/CMakeLists.txt:
  Target "clipper" INTERFACE_INCLUDE_DIRECTORIES property contains relative
  path:

    "include/vxl/v3p/clipper"


CMake Error in v3p/bzlib/CMakeLists.txt:
  Target "bzip2" INTERFACE_INCLUDE_DIRECTORIES property contains relative
  path:

    "include/vxl/v3p/bzlib"

```

At first I thought that Error meant failure... And the return code is 1 instead of zero, but then I noticed it ends with

```
CMake Error in contrib/prip/vpyr/CMakeLists.txt:
  Target "vpyr" INTERFACE_INCLUDE_DIRECTORIES property contains relative
  path:

    "include/vxl/contrib/prip/vpyr"


-- Generating done
-- Build files have been written to: /my_vxl_dir
```

And I appear to be able to run make from there... So are there error I can ignore? Or is something still wrong? I will continue to test to see if everything builds correctly from there
