### ISSUE TITLE
 Borland compiler

### ISSUE THREAD

**Issue by dstoup** [vxl/vxl#24]
VXL has been ported to the Borland 5.5 compiler, but only for the core
libraries, not the contrib libraries.  Brad King did the port for the
core libraries and may have some advice on getting contrib ported.

**Comment by hjmjohnson** [comment]
I have a set of patches that *REMOVES* the Borland compiler support.  This will greatly simplify the VXL toolkit and remove a lot of complexity.

Note:  I al so have patches to remove support for SGI, SunPro, VC5,6,7,8.0.

Hans
