### ISSUE TITLE
including VXL as a subdirectory

### ISSUE THREAD

**Issue by decrispell** [vxl/vxl#250]
@hjmjohnson  We have been including VXL in another project by including it as a subdirectory via CMake's add_directory.   This was broken by 6f4c444e because CMAKE_SOURCE_DIR and CMAKE_BINARY_DIR do not point to the root vxl directory, but the root of the base project.  Would making the paths relative to CMAKE_CURRENT_BINARY_DIR and CMAKE_CURRENT_SOURCE_DIR instead satisfy the original goals of this commit?

**Comment by hjmjohnson** [comment]
Daniel,

Thank you for the note.  I must not have done a good enough job, but there is at least a partial fix in 
https://github.com/vxl/vxl/commit/19e1a5b3409967534f4a461011f96db1535dd469

That attempted to address this problem.  I then to prefer CMAKE_CURRENT_LIST_DIR when possible.  
Note that +set(VXL_ROOT_SOURCE_DIR ${CMAKE_CURRENT_LIST_DIR}) was added to make it easier to find the base of VXL.


Hans

--

**Comment by decrispell** [comment]
Thanks for the tips, Hans.  I believe the remaining issues are now resolved by #253.
