### ISSUE TITLE
vidl_pixel_format_from_ffmpeg’ was not declared in this scope

### ISSUE THREAD

**Issue by minzhee** [vxl/vxl#265]
Hello, everyone,When I build the whole vxl project, I come cross the problems as the following, I 
can not figure out what the reason is and when I search in google I can not find answers. Can any one help? I am new to linux.  Thanks !!
This is produced after the "make" command:

[ 35%] Built target vpgl_io_test_template_include
[ 35%] Built target vpgl_xio
[ 35%] Built target vpgl_xio_test_all
[ 35%] Built target vpgl_xio_test_include
[ 35%] Building CXX object core/vidl/CMakeFiles/vidl.dir/vidl_ffmpeg_istream.cxx.o
In file included from /home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream.cxx:31:0:
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx: In member function ‘virtual bool vidl_ffmpeg_istream::open(const string&)’:
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:147:43: error: ‘av_find_stream_info’ was not declared in this scope
   if ( av_find_stream_info( is_->fmt_cxt_ ) < 0 ) {
                                           ^
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:169:43: error: ‘avcodec_open’ was not declared in this scope
   if ( !codec || avcodec_open( enc, codec ) < 0 ) {
                                           ^
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx: In member function ‘virtual void vidl_ffmpeg_istream::close()’:
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:220:5: warning: ‘void av_close_input_file(AVFormatContext*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1397) [-Wdeprecated-declarations]
     av_close_input_file( is_->fmt_cxt_ );
     ^
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:220:40: warning: ‘void av_close_input_file(AVFormatContext*)’ is deprecated (declared at /usr/include/libavformat/avformat.h:1397) [-Wdeprecated-declarations]
     av_close_input_file( is_->fmt_cxt_ );
                                        ^
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx: In member function ‘virtual vidl_pixel_format vidl_ffmpeg_istream::format() const’:
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:336:69: error: ‘vidl_pixel_format_from_ffmpeg’ was not declared in this scope
   vidl_pixel_format fmt = vidl_pixel_format_from_ffmpeg(enc->pix_fmt);
                                                                     ^
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx: In member function ‘virtual vidl_frame_sptr vidl_ffmpeg_istream::current_frame()’:
/home/minzhe/Downloads/vxl-master/core/vidl/vidl_ffmpeg_istream_v3.hxx:477:71: error: ‘vidl_pixel_format_from_ffmpeg’ was not declared in this scope
     vidl_pixel_format fmt = vidl_pixel_format_from_ffmpeg(enc->pix_fmt);
                                                                       ^
make[2]: *** [core/vidl/CMakeFiles/vidl.dir/vidl_ffmpeg_istream.cxx.o] Error 1
make[1]: *** [core/vidl/CMakeFiles/vidl.dir/all] Error 2
make: *** [all] Error 2

**Comment by decrispell** [comment]
Do you need FFMPEG support?  If not, try setting the "WITH_FFMPEG" CMake variable to false (from within the gui or -DWITH_FFMPEG=False from the cmake command line).  

The underlying issue could be a FFMPEG version incompatibility.

**Comment by minzhee** [comment]
It work!!
Thanks very much !!!!
I've Still a lot learn!!

**Comment by dxqxiaoqiang** [comment]
hello i meet with the same question as you.Could you tell me how you solve this in detail? @minzhee
