### ISSUE TITLE
vcl and CMake trycompile

### ISSUE THREAD

**Issue by dstoup** [vxl/vxl#29]
Bill Hoffman has suggested that a lot of the compiler version based
# ifdefs in vcl could be replaced by the CMake trycompile mechanism.

**Comment by hjmjohnson** [comment]
:+1:   That would be VERY nice.  I would suggest that we do some house-cleaning first.  Removing BORLAND, SGI, VC[5678] removes much of the need for any of this infrastructure.

**Comment by dstoup** [comment]
Agreed!

**Comment by billhoffman** [comment]
VS 8 might be going to far IMO..

**Comment by hjmjohnson** [comment]
@billhoffman 
Bill,  Thanks for the feedback.  I will keep VS8.
Hans

**Comment by hjmjohnson** [comment]
VXL 2.0.0 removed all these try-compile mechanisms.
