### ISSUE TITLE
vnl std::complex instantiation problems with clang + libstdc++

### ISSUE THREAD

**Issue by rfabbri** [vxl/vxl#305]
Hi,
I'm trying to build vxl on OSX using the default clang setup. It builds vnl OK, but since I need GNU extensions in my code, I activated the use of libstdc++ by

CMAKE_CXX_FLAGS = -Wno-gnu-static-float-init -stdlib=libstdc++

( Not sure if I should just switch to GCC entirely in this case. )

But then vnl spits out a link time error only for std::complex specializations of vnl structures:

```
[ 30%] Built target testlib
[ 30%] Linking CXX executable ../../../bin/vnl_test_all
Undefined symbols for architecture x86_64:
  "std::complex<double> dot_product<std::complex<double> >(vnl_vector<std::complex<double> > const&, vnl_vector<std::complex<double> > const&)", referenced from:
      test_vector() in test_complex.cxx.o
  "std::complex<double> inner_product<std::complex<double> >(vnl_vector<std::complex<double> > const&, vnl_vector<std::complex<double> > const&)", referenced from:
      test_vector() in test_complex.cxx.o
...
...
...
```

This did not occur about 6 months ago with the same CXX_FLAGS (when we'd use vcl_complex perhaps). I looked into the instantiation macros and can't find anything wrong. I did a clean rebuild, to no avail.

Thanks,

**Comment by yanggehua** [comment]
Hi Ricardo,

I have been compiling VXL on MAC OS X as well, but not with the latest revisions.  Just a quick check:  did you try to use "-std=c++11"  in the compilation?  It may not help your situation at well. It is just the first idea I come up with looking at your message. 

Gary

**Comment by hjmjohnson** [comment]
I just ran a clean build successfully:

 

mkdir vxl-libstdcxx

cd vxl-libstdcxx

cmake -DCMAKE_CXX_FLAGS:STRING="-Wno-gnu-static-float-init -stdlib=libstdc++" ../vxl

make

 

 

NOTE:  If you change the CMAKE_CXX_FLAGS after initial cmake configuration, you are effectively changing the compiler behavior AFTER all the introspection was done to determine what the compiler features are.  You MUST add these compiler-changing flags BEFORE the introspection is run (i.e. on the initial cmake command line).  

 

Flags like “-stdlib=libstdc++, -std=c++11” effectively change the compiler and all it’s behavior.

 

Hans

**Comment by rfabbri** [comment]
Compilation works, but the problem persists with

BUILD_SHARED_LIBS = ON

I still need shared libs for fast linking large executables during the build-test cycle.

**Comment by rfabbri** [comment]
Some more tests: 
BUILD_SHARED_LIBS = ON  will work without libstdc++ (ie, with libc++).
libstdc++ only works with BUILD_SHARED_LIBS=OFF 
-std=c++11 just never works
