### ISSUE TITLE
CMake build fails

### ISSUE THREAD

**Issue by hasnainv** [vxl/vxl#310]
CMake version: 2.8.11
VXL version: latest (commit 8818a8de3b698b994f66d6fa7831b659751c25d1)

Cant' build vxl with flags BUILD_SHARED_LIBS=ON

The command that is failing is: 
/usr/bin/c++   -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -Dvpl_EXPORTS -fPIC -Ivcl -I../vcl -Icore -I../core    -fPIC;-fvisibility=hidden -fvisibility-inlines-hidden -MMD -MT core/vpl/CMakeFiles/vpl.dir/vpl_fileno.cxx.o -MF "core/vpl/CMakeFiles/vpl.dir/vpl_fileno.cxx.o.d" -o core/v
pl/CMakeFiles/vpl.dir/vpl_fileno.cxx.o -c ../core/vpl/vpl_fileno.cxx

In the above command fPIC flag is repeated twice and has the second time has a ';' after it.
It is clear that the ';' is the issue but I don't know where it is coming from

**Comment by hasnainv** [comment]
@hjmjohnson The issue seems to be from a commit coming from you (commit a38531a2)

If I comment the line COMPILE_FLAGS "${fPIC_COMPILER_FLAGS} in core/vpl/CMakeLists.txt, it compiles fine. 
Since you're adding the fPIC flag here again, note that fPIC flag is already added from the base CMakeLists when BUILD_SHARED_LIBS is ON.

**Comment by hjmjohnson** [comment]
@hasnainv Can you make a pull request if this is still a problem?
I am closing this old issue assuming that it has been addressed.
