### ISSUE TITLE
Remove Support for Visual Studio that report with "_MSC_VER < 1499"

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#32]
This will greatly reduce the code base, and much of the complexity and CMake variable spaghetti code that makes it difficult to track down behaviors.

**Comment by dstoup** [comment]
As mentioned by Bill Hoffman, VS 8 should remain for now.

**Comment by hjmjohnson** [comment]
@dstoup Great.  I have a patch set started, but it depends upon the current outstanding pull request.    Once the current pull request https://github.com/vxl/vxl/pull/11 is merged, I can continue to work on this task.

**Comment by hjmjohnson** [comment]
@billhoffman 

I think that I have my names all confused for windows build environments.  Let me try to figure out what we want to support. I don't know what VS5, VS6, VS7 are any more.  Can we come up with a gameplan based on "_MSC_VER" identifiers so that I do the correct work?

FYI:   It appears that it has been listed as deprecated since 2010 in the code. https://github.com/vxl/vxl/blame/master/vcl/vcl_compiler.h#L155

MSVC++ 14.0 _MSC_VER == 1900 (Visual Studio 2015)
MSVC++ 12.0 _MSC_VER == 1800 (Visual Studio 2013)
MSVC++ 11.0 _MSC_VER == 1700 (Visual Studio 2012)
MSVC++ 10.0 _MSC_VER == 1600 (Visual Studio 2010)
MSVC++ 9.0  _MSC_VER == 1500 (Visual Studio 2008)
MSVC++ 8.0  _MSC_VER == 1400 (Visual Studio 2005)
MSVC++ 7.1  _MSC_VER == 1310 (Visual Studio 2003)
MSVC++ 7.0  _MSC_VER == 1300
MSVC++ 6.0  _MSC_VER == 1200
MSVC++ 5.0  _MSC_VER == 1100


So that I am 100% clear... We *DO* want to support the 10 year old compler identified by MSVC++ 9.0  _MSC_VER == 1500 (Visual Studio 2008)   (  VC_9 ), but we do NOT want to support MSVC++ 8.0  _MSC_VER == 1400 (Visual Studio 2005).

**Comment by billhoffman** [comment]
Sure, that sounds good. MSVC++ 9.0 _MSC_VER == 1500 (Visual Studio 2008) and newer.  So, only a 7 year old compiler 2008=_MSC_VER == 1500.

**Comment by hjmjohnson** [comment]
@dstoup THANKS!
