### ISSUE TITLE
Review instantiation and export specification for VXL

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#328]
==As reviewed by @blowekamp=========================
I fired off an experimental build for VS9 shared.
I just noticed that VNL, does not include the hxx in with the header files:
ITK/Modules/ThirdParty/VNL/src/vxl/core/vnl
grep virtual $(find ./ -name *.h)
For example if you are trying to use vnl_matrix<long double>, and there was no VNL_MATRIX_INSTANTIATE(long double), then you would get linking error. Because the implementation is not available. Only the methods that are intended to be inline are included in the header.
I wonder if the constructors should always be in the hxx, to ensure the dynamic_casts work. Some how we ought to ensure that that each class type has the same runtime type information.
# Just commenting on how the VNL instantiation and export specifications are different that ITK's.

This review took place when updating ITK's reference to VXL.  Some careful considerations need to be made here regarding how safety of these libraries should be handled for dynamic_casts to work.

**Comment by blowekamp** [comment]
Above should read "trying to use vnl_matrix<long double>" and "different than ITK's."

**Comment by hjmjohnson** [comment]
This has been addressed now.
