### ISSUE TITLE
LSQR (and related) Licensing Issues (ITK bug HISTITK-1160)

### ISSUE THREAD

**Issue by tvercaut** [vxl/vxl#332]
In 2010, we identified a licensing issue with some code from vnl and at the time Luis Ibanez fixed it from the ITK side:
https://issues.itk.org/jira/browse/HISTITK-1160

Luis notably rewrote the LSQR code:
https://github.com/InsightSoftwareConsortium/ITK/tree/release-3.20/Utilities/vxl/v3p/netlib/linalg
http://svn.na-mic.org/NAMICSandBox/trunk/SparseLinearSolverConversion/C++/
https://github.com/InsightSoftwareConsortium/ITK/commits/release-3.20/Utilities/vxl/v3p/netlib/linalg

It seems that this effort was not backported to VXL and was subsequently lost when moving to ITK 4:
https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/ThirdParty/VNL/src/vxl/v3p/netlib/linalg

For the only purpose of LSQR, I copied the LSQR NAMICSandBox code in a standalone github repo here:
https://github.com/tvercaut/LSQR-cpp

I have also added a comment in the ITK bug tracker:
https://issues.itk.org/jira/browse/HISTITK-1160

**Comment by thewtex** [comment]
@hjmjohnson @tvercaut I will take a look...

**Comment by QuadmasterXLII** [comment]
Working on it at http://review.source.kitware.com/#/c/21296

**Comment by hjmjohnson** [comment]
Resolved in: https://github.com/vxl/vxl/pull/337
