### ISSUE TITLE
Build Failure: DCMTK

### ISSUE THREAD

**Issue by DVigneault** [vxl/vxl#349]
_Note_: I _am_ able to get this to build if I turn `VXL_FORCE_V3P_DCMTK` `ON`--I only get this error when trying to use the system version (which is the default--and I have confirmed that DCMTK is installed).  However, since I wasn't able to find the root of the issue, I thought I'd share my experience in the hopes of giving someone else a head start.

---

I'm running up against a build failure when building the master branch on Ubuntu 14.04.  Here are the steps I'm taking:

```
$ mkdir bin
$ cd bin
$ ccmake ../src -DCMAKE_CXX_FLAGS=-std=c++11
```

While configuring, I get the following output:

```
 DCMTK Dir

 /usr/include/dcmtk/config/usr/include/usr/include/dcmtk/dcmdata/usr/include/usr/include/dcmtk/dcmimage/usr/include/usr/include/dcmtk/dcmimgle/usr/include/usr/include/dcmtk/dcmjpeg/usr/include/usr/include
 /dcmtk/dcmjpls/usr/include/usr/include/dcmtk/dcmnet/usr/include/usr/include/dcmtk/dcmpstat/usr/include/usr/include/dcmtk/dcmqrdb/usr/include/usr/include/dcmtk/dcmsign/usr/include/usr/include/dcmtk/dcmsr/
 usr/include/usr/include/dcmtk/dcmtls/usr/include/usr/include/dcmtk/ofstd/usr/include/usr/include/dcmtk/oflog/usr/include/usr/include/usr/include/dcmtk

 BSTM FOUND OPENCL
```

In the advanced options, `DCMTK_DIR` is set to `/usr`.  I tried resetting it to `/usr/include/dcmtk/`, but it reverts to `/usr` upon configuring.  (I've confirmed that `libdcmtk2-dev` is installed.)  After a few rounds of configuring, I _am_ allowed to generate, and but get the following error while building:

```
In file included from /usr/include/dcmtk/ofstd/ofstring.h:65:0,
118                  from /usr/include/dcmtk/ofstd/offile.h:34,
119                  from /usr/include/dcmtk/dcmdata/dcsequen.h:35,
120                  from /usr/include/dcmtk/dcmdata/dcfilefo.h:35,
121                  from /local/pemb3433/Developer/vxl/src/core/vil/file_formats/vil_dicom.cxx:31:
122 /usr/include/dcmtk/ofstd/ofstream.h:67:22: fatal error: iostream.h: No such file or directory
123 compilation terminated.
```

The CMake output I got while configuring looked suspicious to me--I would have assumed that there would be `:` characters separating the paths--so I grepped around and found the `DCMTK_PATH_SEPARATOR` variable in a [config file](https://github.com/vxl/vxl/blob/a9ae25fd362087179fc93723c24ee66c38409bd1/v3p/dcmtk/config/include/osconfig_cmake.h.in#L30:L32), but this file hasn't been changed in quite a while, and it's unclear where this issue is coming from.

Hope this is helpful,

--Davis

**Comment by hjmjohnson** [comment]
Pull requests welcome if this is still an issue.
