### ISSUE TITLE
vidl

### ISSUE THREAD

**Issue by dxqxiaoqiang** [vxl/vxl#388]
when I compile Probabilistic-Volumetric-3D-Reconstruction I meet with the  follow errors :
../../../lib/libvidl.a(vidl_ffmpeg_istream.cxx.o): In function `vidl_ffmpeg_istream::open(std::string const&)':
vidl_ffmpeg_istream.cxx:(.text+0x3d5): undefined reference to `av_frame_alloc'
../../../lib/libvidl.a(vidl_ffmpeg_ostream.cxx.o): In function `vidl_ffmpeg_ostream::close()':
vidl_ffmpeg_ostream.cxx:(.text+0x124f): undefined reference to `av_packet_unref'
../../../lib/libvidl.a(vidl_ffmpeg_ostream.cxx.o): In function `vidl_ffmpeg_ostream::write_frame(vil_smart_ptr<vidl_frame> const&)':
vidl_ffmpeg_ostream.cxx:(.text+0x16f5): undefined reference to `av_frame_alloc'
vidl_ffmpeg_ostream.cxx:(.text+0x1b3b): undefined reference to `av_packet_unref'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/vidl_transcode_video] Error 1
make[1]: *** [core/vidl/examples/CMakeFiles/vidl_transcode_video.dir/all] Error 2
make: *** [all] Error 2
what I can do  with this error? @decrispell

**Comment by hjmjohnson** [comment]
Unable to reproduce.
