### ISSUE TITLE
 undefined reference to symbol 'lzma_code@@XZ_5.0'

### ISSUE THREAD

**Issue by kensully** [vxl/vxl#411]
I am on Ubuntu 16.04 32 bit platform. I cloned this repository, created `build` folder in `vxl` directory and ran `cmake ..` then `make`. I don't know if I followed the required steps for my distro, there is no build document. It failed with the following error:
      
      [ 33%] Built target vidl_v4l2_example
      [ 33%] Linking CXX executable ../../../bin/vidl_transcode_video
      /usr/bin/ld.bfd.real: /usr/local/lib/libavcodec.a(tiff.o): undefined reference to symbol       'lzma_code@@XZ_5.0'
      //lib/i386-linux-gnu/liblzma.so.5: error adding symbols: DSO missing from command line
      collect2: error: ld returned 1 exit status
      core/vidl/examples/CMakeFiles/vidl_transcode_video.dir/build.make:110: recipe for target       'bin/vidl_transcode_video' failed
      make[2]: *** [bin/vidl_transcode_video] Error 1
      CMakeFiles/Makefile2:9990: recipe for target       'core/vidl/examples/CMakeFiles/vidl_transcode_video.dir/all' failed
      make[1]: *** [core/vidl/examples/CMakeFiles/vidl_transcode_video.dir/all] Error 2
      Makefile:140: recipe for target 'all' failed
      make: *** [all] Error 2

**Comment by decrispell** [comment]
I don't know anything about this particular issue, but I know there have been problems with ffmpeg / libav incompatibilities in the past.

If you don't need video processing capabilities,  you could try building with WITH_FFMPEG set to FALSE.  You can set it via the cmake gui or on the cmake command line via -DWITH_FFMPEG=FALSE   (See #156 for reference).

**Comment by kensully** [comment]
@decrispell  thank you for the reply. I ll use this library to compile `https://sourceforge.net/projects/opengazer/` ,  would disabling `ffmpeg` make it useless?

**Comment by decrispell** [comment]
I don't know anything about how that project uses vxl.  Worth a try, I'd say.

**Comment by decrispell** [comment]
@kensully Any luck with this?

**Comment by kensully** [comment]
@decrispell I just  compiled `vxl` with ` -DWITH_FFMPEG=FALSE` I ll report the result soon.

**Comment by kensully** [comment]
I tried to build `opengazer` with `vxl`, I get compilation errors such as:
     utils.h: In function ‘std::ostream& operator<<(std::ostream&, const std::vector<T>&)’:
utils.h:38:14: error: expected ‘;’ before ‘iter’
     xforeach(iter, vec)

 it seems `opengazer` is outdated and not compatible with latest `vxl` library. I also found out that Ubuntu already has `vxl 1.17` library in its repository.

**Comment by hjmjohnson** [comment]
It seems that alternate solution was found for VXL.
