### ISSUE TITLE
Very long running test: vpgl_algo_test_bundle_adjust

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#452]
@decrispell 

David,

This test in the vpgl suite takes about 87% of all the test timings.

386/386 Test #370: vpgl_algo_test_bundle_adjust ......................   Passed   87.06 sec
Total Test time (real) = 102.56 sec

core/vpgl/algo/tests/test_bundle_adjust.cxx

Could you take a quick look to see if it would be easy to reduce that time?

A quick review seems like perhaps it is doing millions of the same test (ie. testing over every pixel of a normal sized image).   It would be great if this could take only a few seconds.

Thanks,
Hans

**Comment by decrispell** [comment]
I don't see anything obviously bad like you describe, but the tests do take more than a couple of seconds to complete.  I'll take a look to see if there's anything that can be done to speed them up without losing functionality.

**Comment by hjmjohnson** [comment]
@decrispell Thinking about this a bit more, perhaps the problem is that I am running parallel ctest and the test dependancies are causing these two to fail.

Could you take a quick look and see if the inputs to this test require the outputs of another test.?

I was getting timeout failures at 1500 seconds.

**Comment by decrispell** [comment]
@hjmjohnson No, I don't see anything like that.   There are some calls to a non-linear optimizer that take some time (couple of seconds each on my laptop) to converge, but 1500 seconds sounds pretty extreme.  Was the system under intense load when this happened?

**Comment by hjmjohnson** [comment]
No.  

 

ctest -j 4. And nothing else.

 

Let’s let this be for now perhaps this was a false alarm.    Now that other failures are cleared up, it should be easier to isolate if a problem is real.

 

Hans

**Comment by hjmjohnson** [comment]
closing, can not reproduce today.
