### ISSUE TITLE
SSE code is failing on Mac and Linux\

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#458]
See #456 

Disabling VNL_CONFIG_ENABLE_SSE2 as a valid option 

Many tests are failing (and failing inconsistently from run to run).

My guess is that the test pass when alignment happens to be correct and fails otherwise.

@thewtex

**Comment by hjmjohnson** [comment]
@thewtex Matt you asked me to create and assign this to you (see https://github.com/vxl/vxl/pull/456)

I can not assign this to you.  

I'm trying to clean the VXL issue tracker up a bit.

**Comment by hjmjohnson** [comment]
Accidently closed.

**Comment by thewtex** [comment]
@hjmjohnson I do not have any permissions / access roles in the GitHub `vxl/vxl` repository, which is why you cannot assign this to me.

However, I think it is time for ITK to focus on moving past VNL, so I do not think this is something that I would work on anyway.

**Comment by hjmjohnson** [comment]
+100!  Thanks.  I'll close this. 

VXL has been upsetting me.  My primary motivation for working on VNL is to evolve it towards something that will be easier to replace.
