### ISSUE TITLE
OPENJPEG2 ERRORs?

### ISSUE THREAD

**Issue by jiapei100** [vxl/vxl#465]
Hi, Prof. Tim Cootes:

It's me again... I happened to come across your libary on github today. Just wanna try it out, but failed to build... Sorry to trouble you again...

I'm using Ubuntu 16.04.4, and openjpeg-2.3 (downloaded from [http://www.openjpeg.org/](http://www.openjpeg.org/) and manually built ) . 

However, I still met the following ERROR messages:

> 
> [ 51%] Building CXX object core/vil/CMakeFiles/vil.dir/file_formats/vil_openjpeg.cxx.o
> cd /media/jiapei/Data/Downloads/computervision/vxl/build/core/vil && /usr/bin/c++  -DVXL_LEGACY_ERROR_REPORTING -DVXL_WARN_DEPRECATED -DVXL_WARN_DEPRECATED_ONCE -I/media/jiapei/Data/Downloads/computervision/vxl/build/vcl -I/media/jiapei/Data/Downloads/computervision/vxl/vcl -I/media/jiapei/Data/Downloads/computervision/vxl/build/core -I/media/jiapei/Data/Downloads/computervision/vxl/core -I/usr/local/include -I/usr/local/include/openjpeg-2.3 -I/usr/include/x86_64-linux-gnu -I/usr/include/geotiff -I/media/jiapei/Data/Downloads/computervision/vxl/core/vil  -fPIC -O3 -DNDEBUG   -Wno-undefined-var-template -o CMakeFiles/vil.dir/file_formats/vil_openjpeg.cxx.o -c /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘bool vil_openjpeg_decoder::init_stream(void*)’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:257:49: error: too few arguments to function ‘void opj_stream_set_user_data(void**, void*, opj_stream_free_user_data_fn)’
>    opj_stream_set_user_data(this->stream_, stream);
>                                                  ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1194:27: note: declared here
>  OPJ_API void OPJ_CALLCONV opj_stream_set_user_data(opj_stream_t* p_stream,
>                            ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:259:73: error: invalid conversion from ‘vxl_uint_32 (*)(void*, vxl_uint_32, void*) {aka unsigned int (*)(void*, unsigned int, void*)}’ to ‘opj_stream_read_fn {aka long unsigned int (*)(void*, long unsigned int, void*)}’ [-fpermissive]
>                                 vil_openjpeg_decoder::opj_vil_stream_read);
>                                                                          ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1161:27: note:   initializing argument 2 of ‘void opj_stream_set_read_function(void**, opj_stream_read_fn)’
>  OPJ_API void OPJ_CALLCONV opj_stream_set_read_function(opj_stream_t* p_stream,
>                            ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:261:75: error: invalid conversion from ‘vxl_uint_32 (*)(void*, vxl_uint_32, void*) {aka unsigned int (*)(void*, unsigned int, void*)}’ to ‘opj_stream_write_fn {aka long unsigned int (*)(void*, long unsigned int, void*)}’ [-fpermissive]
>                                  vil_openjpeg_decoder::opj_vil_stream_write);
>                                                                            ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1169:27: note:   initializing argument 2 of ‘void opj_stream_set_write_function(void**, opj_stream_write_fn)’
>  OPJ_API void OPJ_CALLCONV opj_stream_set_write_function(opj_stream_t* p_stream,
>                            ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:263:73: error: invalid conversion from ‘vxl_uint_32 (*)(vxl_uint_32, void*) {aka unsigned int (*)(unsigned int, void*)}’ to ‘opj_stream_skip_fn {aka long int (*)(long int, void*)}’ [-fpermissive]
>                                 vil_openjpeg_decoder::opj_vil_stream_skip);
>                                                                          ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1177:27: note:   initializing argument 2 of ‘void opj_stream_set_skip_function(void**, opj_stream_skip_fn)’
>  OPJ_API void OPJ_CALLCONV opj_stream_set_skip_function(opj_stream_t* p_stream,
>                            ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:265:73: error: invalid conversion from ‘bool (*)(vxl_uint_32, void*) {aka bool (*)(unsigned int, void*)}’ to ‘opj_stream_seek_fn {aka int (*)(long int, void*)}’ [-fpermissive]
>                                 vil_openjpeg_decoder::opj_vil_stream_seek);
>                                                                          ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1185:27: note:   initializing argument 2 of ‘void opj_stream_set_seek_function(void**, opj_stream_seek_fn)’
>  OPJ_API void OPJ_CALLCONV opj_stream_set_seek_function(opj_stream_t* p_stream,
>                            ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘bool vil_openjpeg_decoder::read_header()’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:328:40: error: invalid conversion from ‘opj_image_t** {aka opj_image**}’ to ‘void**’ [-fpermissive]
>                            this->stream_) && !this->error_;
>                                         ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:328:40: error: cannot convert ‘vxl_int_32* {aka int*}’ to ‘opj_image_t** {aka opj_image**}’ for argument ‘3’ to ‘OPJ_BOOL opj_read_header(void**, void**, opj_image_t**)’
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘bool vil_openjpeg_decoder::set_decode_area(unsigned int, unsigned int, unsigned int, unsigned int)’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:338:56: error: invalid conversion from ‘unsigned int’ to ‘opj_image_t* {aka opj_image*}’ [-fpermissive]
>    return opj_set_decode_area( this->codec_, x, y, w, h ) && !this->error_;
>                                                         ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:338:56: error: too few arguments to function ‘OPJ_BOOL opj_set_decode_area(void**, opj_image_t*, OPJ_INT32, OPJ_INT32, OPJ_INT32, OPJ_INT32)’
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1395:31: note: declared here
>  OPJ_API OPJ_BOOL OPJ_CALLCONV opj_set_decode_area(opj_codec_t *p_codec,
>                                ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘opj_image_t* vil_openjpeg_decoder::decode()’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:357:48: error: too few arguments to function ‘OPJ_BOOL opj_decode(void**, void**, opj_image_t*)’
>    return opj_decode(this->codec_, this->stream_);
>                                                 ^
> In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:33:0:
> /usr/local/include/openjpeg-2.3/openjpeg.h:1408:31: note: declared here
>  OPJ_API OPJ_BOOL OPJ_CALLCONV opj_decode(opj_codec_t *p_decompressor,
>                                ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In constructor ‘vil_openjpeg_image::vil_openjpeg_image(vil_stream*, vil_openjpeg_format)’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:506:61: error: ‘CODEC_JP2’ was not declared in this scope
>      case VIL_OPENJPEG_JP2: this->impl_->opj_codec_format_ = CODEC_JP2; break;
>                                                              ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:507:61: error: ‘CODEC_JPT’ was not declared in this scope
>      case VIL_OPENJPEG_JPT: this->impl_->opj_codec_format_ = CODEC_JPT; break;
>                                                              ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:508:61: error: ‘CODEC_J2K’ was not declared in this scope
>      case VIL_OPENJPEG_J2K: this->impl_->opj_codec_format_ = CODEC_J2K; break;
>                                                              ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘bool vil_openjpeg_image::validate_format()’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:572:8: error: ‘CODEC_JP2’ was not declared in this scope
>    case CODEC_JP2 :
>         ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:586:8: error: ‘CODEC_JPT’ was not declared in this scope
>    case CODEC_JPT: break; // Although supported by OpenJPEG, the JPT codec
>         ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:589:8: error: ‘CODEC_J2K’ was not declared in this scope
>    case CODEC_J2K:
>         ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx: In member function ‘virtual const char* vil_openjpeg_image::file_format()’:
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:718:10: error: ‘CODEC_JP2’ was not declared in this scope
>      case CODEC_JP2: return "jp2";
>           ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:719:10: error: ‘CODEC_JPT’ was not declared in this scope
>      case CODEC_JPT: return "jpt";
>           ^
> /media/jiapei/Data/Downloads/computervision/vxl/core/vil/file_formats/vil_openjpeg.cxx:720:10: error: ‘CODEC_J2K’ was not declared in this scope
>      case CODEC_J2K: return "j2k";
>           ^
> At global scope:
> cc1plus: warning: unrecognized command line option ‘-Wno-undefined-var-template’
> core/vil/CMakeFiles/vil.dir/build.make:143: recipe for target 'core/vil/CMakeFiles/vil.dir/file_formats/vil_openjpeg.cxx.o' failed
> make[2]: *** [core/vil/CMakeFiles/vil.dir/file_formats/vil_openjpeg.cxx.o] Error 1
> make[2]: Leaving directory '/media/jiapei/Data/Downloads/computervision/vxl/build'
> CMakeFiles/Makefile2:2122: recipe for target 'core/vil/CMakeFiles/vil.dir/all' failed
> make[1]: *** [core/vil/CMakeFiles/vil.dir/all] Error 2
> make[1]: Leaving directory '/media/jiapei/Data/Downloads/computervision/vxl/build'
> Makefile:132: recipe for target 'all' failed
> make: *** [all] Error 2
> 
>

Any suggestions?

Cheers
Pei

**Comment by TimCootes** [comment]
Try editting the CMakeCache.txt file (in your object/binary directory), changing:

VXL_FORCE_V3P_JPEG:BOOL=ON

That should force it to use JPG which comes with VXL (in the v3p subdirectory), which hopefully will be compatible.

Tim

Tim Cootes,  Professor of Computer Vision
Centre for Imaging Sciences,  Faculty of Biology Medicine and Health,
The University of Manchester, Manchester M13 9PT, UK
Tel:   (+44) 0161 275 5146
http://personalpages.manchester.ac.uk/staff/timothy.f.cootes/

________________________________

**Comment by jiapei100** [comment]
Hi, Thank you Prof. Tim Cootes. ^_^

In my case, it is  **VXL_FORCE_V3P_OPENJPEG2:BOOL=ON** that makes some progress. However, in my case, there are still some other ERRORs. I've got to do:

1. WITH_FFMPEG:BOOL=OFF
If it's ON, I got the following ERROR message. (Sorry, I'm NOT using anything from repo, but manually build FFMPEG. )

```
In file included from /media/jiapei/Data/Downloads/computervision/vxl/core/vidl/vidl_ffmpeg_ostream.cxx:39:0:
/media/jiapei/Data/Downloads/computervision/vxl/core/vidl/vidl_ffmpeg_ostream_v56.hxx:375:24: error: ‘CODEC_FLAG_PSNR’ was not declared in this scope
     video_enc->flags|= CODEC_FLAG_PSNR;
                        ^
/media/jiapei/Data/Downloads/computervision/vxl/core/vidl/vidl_ffmpeg_ostream_v56.hxx:377:14: error: ‘AVCodecContext {aka struct AVCodecContext}’ has no member named ‘me_method’
   video_enc->me_method = params_.me_method_;
              ^
/media/jiapei/Data/Downloads/computervision/vxl/core/vidl/vidl_ffmpeg_ostream_v56.hxx:384:27: error: ‘CODEC_FLAG_PASS1’ was not declared in this scope
       video_enc->flags |= CODEC_FLAG_PASS1;
                           ^
/media/jiapei/Data/Downloads/computervision/vxl/core/vidl/vidl_ffmpeg_ostream_v56.hxx:388:27: error: ‘CODEC_FLAG_PASS2’ was not declared in this scope
       video_enc->flags |= CODEC_FLAG_PASS2;
                           ^
```


2. VXL_USE_DCMTK:BOOL=OFF
Probably because my DCMTK is also manually built, rather than grabbed directly from the repo.
The include directory is like:
```
/usr/local/include/dcmtk$ ls
config  dcmdata  dcmfg  dcmimage  dcmimgle  dcmiod  dcmjpeg  dcmjpls  dcmnet  dcmpmap  dcmpstat  dcmqrdb  dcmrt  dcmseg  dcmsign  dcmsr  dcmtls  dcmtract  dcmwlm  oflog  ofstd
```

And, I may have to modify two files:
```
$ git diff
diff --git a/core/vil/file_formats/vil_dicom.cxx b/core/vil/file_formats/vil_dicom.cxx
index dc710e2..3670d56 100644
--- a/core/vil/file_formats/vil_dicom.cxx
+++ b/core/vil/file_formats/vil_dicom.cxx
@@ -28,13 +28,13 @@
 #include <vil/vil_pixel_format.h>
 #include <vil/vil_exception.h>
 
-#include <dcfilefo.h>
-#include <dcmetinf.h>
-#include <dcdatset.h>
-#include <dctagkey.h>
-#include <dcdeftag.h>
-#include <dcstack.h>
-#include <diinpxt.h>
+#include <dcmdata/dcfilefo.h>
+#include <dcmdata/dcmetinf.h>
+#include <dcmdata/dcdatset.h>
+#include <dcmdata/dctagkey.h>
+#include <dcmdata/dcdeftag.h>
+#include <dcmdata/dcstack.h>
+#include <dcmimgle/diinpxt.h>
 
 #include "vil_dicom_stream.h"
 //
diff --git a/core/vil/file_formats/vil_dicom_stream.h b/core/vil/file_formats/vil_dicom_stream.h
index 79a6396..b26006e 100644
--- a/core/vil/file_formats/vil_dicom_stream.h
+++ b/core/vil/file_formats/vil_dicom_stream.h
@@ -4,7 +4,7 @@
 // \file
 // \author Amitha Perera
 
-#include <dcistrma.h>
+#include <dcmdata/dcistrma.h>
 
 class vil_stream;
```

Anyway... VXL is now successfully built...

Thank you ...

Pei

**Comment by Rastaban** [comment]
It looks like vxl is using the older version of the API that was deprecated and later removed from openjpeg in https://github.com/uclouvain/openjpeg/commit/7aece5e8e7d4214d140a45aca50a824ff8092924.
