### ISSUE TITLE
undefined reference to `vnl_nonlinear_minimizer

### ISSUE THREAD

**Issue by shomedas** [vxl/vxl#466]
While trying to compile a code(GoGMA) which uses VXL I get the following error.

[ 75%] Building CXX object CMakeFiles/gogma.dir/string_tokenizer.cpp.o
[ 87%] Building CXX object CMakeFiles/gogma.dir/svm.cpp.o
[100%] Linking CXX executable gogma
CMakeFiles/gogma.dir/gogma_generated_gogma.cu.o:(.rodata._ZTV10vnl_lbfgsb[_ZTV10vnl_lbfgsb]+0x28): undefined reference to `vnl_nonlinear_minimizer::is_a() const'
CMakeFiles/gogma.dir/gogma_generated_gogma.cu.o:(.rodata._ZTV10vnl_lbfgsb[_ZTV10vnl_lbfgsb]+0x30): undefined reference to `vnl_nonlinear_minimizer::is_class(std::string const&) const'
collect2: error: ld returned 1 exit status
CMakeFiles/gogma.dir/build.make:235: recipe for target 'gogma' failed
make[2]: *** [gogma] Error 1

I have tried with the lbvxl from git as well libvxl from ubuntu repo. I get the same error for both. I am using ubuntu 16.04, cuda-8.0, nvidia GTX 980 Ti

**Comment by hjmjohnson** [comment]
Can not reproduce with the latest code base.
