### ISSUE TITLE
New version number?

### ISSUE THREAD

**Issue by hmaarrfk** [vxl/vxl#488]
I'm wondering if there are any plans for updating the version number?

I've been having trouble compiling things because I didn't notice that there seems to have been small changes that make the tagged version of 1.17.0 not really compatible with modern builds of InsightToolkit.

Even a minor version bump so that 1.17.1 matches the version that is bundled with InsightToolkit 4.13 would be nice!

**Comment by hjmjohnson** [comment]
New tagged version v1.18.0 provided on October 15th.

**Comment by hmaarrfk** [comment]
Thanks!
