### ISSUE TITLE
BRL: brip / brad cyclic dependency

### ISSUE THREAD

**Issue by rfabbri** [vxl/vxl#497]
brl/bbas/brad depends on brl/bseg/brip  (this shouldn't occur - a bbas library should not depend on a bseg library)

brl/bseg/brip depends on brl/bseg/brad

See brip_ms_blob_detection.{cxx,h} which uses brad

Can someone sort this out?

**Comment by rfabbri** [comment]
Solved. 

bbas/brad was linking to brip, without actually using brip. so I removed it from the corresponding target_link_libraries

bseg/brip now links to brad

This bug was likely unseen by someone using static libraries and just compiling/fixing bugs in an adhoc manner. I use dynamic linking so the linker may be pickier. Will close this issue once a patch is incorporated.

**Comment by hjmjohnson** [comment]
@rfabbri  Please see #508.  Is there any chance that this can be fixed soon?  I lost about 4 hours of work trying to figure this out.  In the end I just turned off building BRL.

**Comment by hjmjohnson** [comment]
See https://github.com/vxl/vxl/pull/518 which resolves this issue.

**Comment by hjmjohnson** [comment]
resolved.
