### ISSUE TITLE
Should we update timestamp of the inferiors in unlink_inferior() function?

### ISSUE THREAD

**Issue by liuhanyao98** [vxl/vxl#501]
In vtol_topology_object.cxx::unlink_inferior() , after unlink this object from its inferior's superior list, should we add a line of code to update timestamp of those inferiors also?

'inferior->touch();'

in vtol_topology_object.cxx::link_inferior(), this statement exists. I think maybe unlink_inferior() function misses this statement and this problem triggers bugs in our project.

**Comment by hjmjohnson** [comment]
Please make a pull request and reference this topic.
