### ISSUE TITLE
vnl_complex test fails on gcc 4.9

### ISSUE THREAD

**Issue by dstoup** [vxl/vxl#55]
The /= operator test is failing on newer gcc. I looked into this failure a little bit and don't quite understand. The test seems correct when I do that calculation by hand.

**Comment by hjmjohnson** [comment]
@dstoup 

See: ENH: Instrument test_complex to help identify failure #167  Trying to figure out what is going on.

**Comment by hjmjohnson** [comment]
This issue does not seem to persist.  Perhaps it has been fixed already with the mentioned merge..
