### ISSUE TITLE
migrate vxl homepage to github

### ISSUE THREAD

**Issue by bradking** [vxl/vxl#555]
Cc: @hjmjohnson 

The http://vxl.sourceforge.net homepage is out of date and only a few people have access to update it (I'm one of them).  I propose that we migrate the VXL homepage to `vxl.github.io` by adding an appropriate GitHub Pages repository.

**Comment by bradking** [comment]
I've created the [vxl.github.io repository](https://github.com/vxl/vxl.github.io) and populated it with the same history as the original [sf www repo](https://sourceforge.net/p/vxl/git-www/) (which can be cloned via [this url](https://git.code.sf.net/p/vxl/git-www).

Now the homepage content can be seen at https://vxl.github.io/.

It does need some updates.

**Comment by bradking** [comment]
@hjmjohnson if you agree with this approach I can update the old site to just point to the new URL.

**Comment by hjmjohnson** [comment]
@bradking This is GREAT!  Please do have the old site simply point to this new site.

**Comment by hjmjohnson** [comment]
@bradking I'll make a pass over the web page in the next month (after classes end in 2 weeks) to update the content.

**Comment by bradking** [comment]
@hjmjohnson great.  I've put the redirects in place from the original URLs.

**Comment by hjmjohnson** [comment]
@bradking overdue, but Thanks for this effort of continuing to move vxl from sourceforge to github.
