### ISSUE TITLE
VXL 2.0.2 compilation error

### ISSUE THREAD

**Issue by SergiiPatar** [vxl/vxl#565]
Hi,

I just downloaded the new release of VXL 2.0.2. I'm trying to build it, however, I obtain an error.

I use VS 2017 (15.9.3)
CMake 3.13.1
I tried both Win32 and Win64 bit compilations, and the error is the same.

Her is the error:

D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_vector_io.hxx(115): error C2668: 'vsl_print_summary': ambiguous call to overloaded function (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(418): note: could be 'void vsl_print_summary(std::ostream &,double)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(409): note: or       'void vsl_print_summary(std::ostream &,float)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(376): note: or       'void vsl_print_summary(std::ostream &,unsigned long)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(368): note: or       'void vsl_print_summary(std::ostream &,long)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(360): note: or       'void vsl_print_summary(std::ostream &,unsigned short)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(352): note: or       'void vsl_print_summary(std::ostream &,short)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(344): note: or       'void vsl_print_summary(std::ostream &,unsigned int)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(334): note: or       'void vsl_print_summary(std::ostream &,int)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(288): note: or       'void vsl_print_summary(std::ostream &,unsigned char)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(280): note: or       'void vsl_print_summary(std::ostream &,signed char)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(272): note: or       'void vsl_print_summary(std::ostream &,char)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_binary_io.h(264): note: or       'void vsl_print_summary(std::ostream &,bool)' (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl/vsl_vector_io.hxx(115): note: while trying to match the argument list '(std::ostream, const _Ty)'
1>        with
1>        [
1>            _Ty=vxl_uint_64
1>        ] (compiling source file D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx)
1>D:\ExternalLibs\v6\vxl\2.0.2\src\core\vsl\Templates\vsl_vector_io+uint_64-.cxx(5): note: see reference to function template instantiation 'void vsl_print_summary<vxl_uint_64>(std::ostream &,const std::vector<vxl_uint_64,std::allocator<_Ty>> &)' being compiled
1>        with
1>        [
1>            _Ty=vxl_uint_64
1>        ]

**Comment by hjmjohnson** [comment]
This was fixed yesterday:  https://github.com/vxl/vxl/pull/564
