### ISSUE TITLE
VXL 2.0.2  build failure Centos7, gcc-4.8.5, Cmake 3.13.4

### ISSUE THREAD

**Issue by jonarbo** [vxl/vxl#639]
HI, 

I'm doing: 

cmake3 $VXLSRC -DCMAKE_INSTALL_PREFIX=/usr/pubsw/packages/vxl/current
make && make install 

the cmake goes OK, the make fails:

[ 47%] Built target vgl_test_template_include
[ 47%] Built target vgl_test_include
[ 49%] Built target vgl_test_all
[ 49%] Building CXX object core/vil/CMakeFiles/vil.dir/file_formats/vil_dicom.cxx.o
In file included from /scratch/apps/singularity-sandboxes/braimcore-sandbox/SOFTWARE/FREESURFER/vxl-git/vxl/core/vil/file_formats/vil_dicom.cxx:38:0:
/scratch/apps/singularity-sandboxes/braimcore-sandbox/SOFTWARE/FREESURFER/vxl-git/vxl/core/vil/file_formats/vil_dicom_stream.h: In member function ‘virtual DcmInputStreamFactory* vil_dicom_stream_factory::clone() const’:
/scratch/apps/singularity-sandboxes/braimcore-sandbox/SOFTWARE/FREESURFER/vxl-git/vxl/core/vil/file_formats/vil_dicom_stream.h:44:46: error: cannot allocate an object of abstract type ‘vil_dicom_stream_factory’
     return new vil_dicom_stream_factory(*this);
                                              ^
/scratch/apps/singularity-sandboxes/braimcore-sandbox/SOFTWARE/FREESURFER/vxl-git/vxl/core/vil/file_formats/vil_dicom_stream.h:32:7: note:   because the following virtual functions are pure within ‘vil_dicom_stream_factory’:
 class vil_dicom_stream_factory

**Comment by dzenanz** [comment]
Does #722 fix this?

**Comment by hjmjohnson** [comment]
I think this issue was resolved with #722
