### ISSUE TITLE
protect master branch

### ISSUE THREAD

**Issue by decrispell** [vxl/vxl#681]
I believe we should prevent direct pushes to the master branch and require changes to pass through pull requests.  This should be possible via github's "protected branches" feature.

Even if the PR is "self-merged", it at least gives the integration tests a chance to run, and sends a notification to the "watchers" of the repository.

**Comment by hjmjohnson** [comment]
@bradking @thewtex I do not have permissions to protect the master branch.  This is a great idea.  Could one of you please coordinate the protection of the master branch on github?

**Comment by bradking** [comment]
I've enabled "Require status checks to pass before merging" on the `master` branch and marked the `continuous-integration/travis-ci` check as required.
