### ISSUE TITLE
BRL: Comment out BRL Failing Tests, To be addressed and re-added

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#71]
Related to issues here vxl#54

Tests tagged with "HACK_FORCE_BRL_FAILING_TESTS" for easy identification

To get these tests to run use "cmake -DHACK_FORCE_BRL_FAILING_TESTS:BOOL=ON"

These are the tests that fail on my Mac: ==================================
99% tests passed, 6 tests failed out of 980 
- bocl_test_command_queue (SEGFAULT) <— identified memory access after free, but don’t know how to fix 
- boxm2_test_merge_function (Failed) 
- boxm2_ocl_test_kernel_filter (Failed) 
- boxm2_ocl_test_kernel_vector_filter (Failed)
- boxm2_test_io (Timeout) ***Timeout 1500.04 sec <— Identified an infinite loop, but don’t know how to fix 

These are tests that fail on Linux (some on travis CI, some on RHEL6) ================================== 
99% tests passed, 3 tests failed out of 956 
- bsta_algo_test_mean_shift (Failed) 
- imesh_test_generate_mesh (OTHER_FAULT)  (segfault during memory free operation)
- boxm_algo_sp_test_update (OTHER_FAULT) 
- boxm_test_cell_iterator (SEGFAULT)
- bvpl_test_detect_corner (Failed)

**Comment by hjmjohnson** [comment]
@decrispell @ozgecanoz 

This pull request addresses your desired behavior w.r.t. BRL failing tests.
https://github.com/vxl/vxl/pull/66  (A quick review would be GREATLY appreciated, as this is holding up a few other issues).

https://open.cdash.org/buildSummary.php?buildid=4161696  (1 failing test addressed elsewhere)
https://open.cdash.org/buildSummary.php?buildid=4161699

**Comment by decrispell** [comment]
@hjmjohnson  done.

**Comment by hjmjohnson** [comment]
Mac Clang Compiler warnings to be addressed:

[mac_comp_warn.txt](https://github.com/vxl/vxl/files/71219/mac_comp_warn.txt)

**Comment by hjmjohnson** [comment]
GREAT!
