### ISSUE TITLE
https://vxl.github.io package/book documentation fails to load

### ISSUE THREAD

**Issue by brad-t-moore** [vxl/vxl#743]
### Description

None of the documentation links at https://vxl.github.io/ load.
The VXL book links hosted at Kitware return 404 errors.
The package documentation at Kitware returns a 404, the Brown and Manchester links timeout.

### Expected information

The links should work or the links should be removed.

### Actual information

https://public.kitware.com/vxl/doc/release/index.html (returns 404)

**Comment by hjmjohnson** [comment]
@brad-t-moore Has this issue been resolved?

**Comment by brad-t-moore** [comment]
Yes, thank you!
