### ISSUE TITLE
BRL: Failing Tests comment out, due to in-consistent initialized value

### ISSUE THREAD

**Issue by yidongVSI** [vxl/vxl#80]
in contrib/brl/bseg/bvxm/tests/test_voxel_world_mog_image.cxx:

Following test is comment out
TEST_NEAR("image diff should sum to 0", sum, 0.0f, 5.0f);

This test failure was due to difference in initial values used in two expected image from bvxm voxel world.  Other than that, the rendered results were exactly same.

**Comment by yidongVSI** [comment]
The issue is solved on both Windows and Linux.  Will close once test on Mac go through

**Comment by hjmjohnson** [comment]
Issue claims to be solved.
