### ISSUE TITLE
Install tree does not install headers

### ISSUE THREAD

**Issue by phcerdan** [vxl/vxl#801]
No headers can be found in the install tree other than:
![image](https://user-images.githubusercontent.com/3021667/95274133-48147d00-0845-11eb-89c4-8051056654a8.png)

This has been introduced by the recent refactor of CMake files by @drewgilliam. Using the commit just before those changes the headers are installed.

Reported in ITK: https://github.com/InsightSoftwareConsortium/ITK/pull/2034

**Comment by drewgilliam** [comment]
Fixed with PR #802

**Comment by phcerdan** [comment]
That was fast, thanks @drewgilliam
