### ISSUE TITLE
The value of sqrt(2π) is wrong

### ISSUE THREAD

**Issue by Leengit** [vxl/vxl#828]
### Description
The value of sqrt(2π) is wrong.

### Expected behavior
core/vnl/vnl_math.h:113 should be
```c++
static constexpr double sqrt2pi          = 2.50662827463100050242;
```
See http://oeis.org/A019727/constant or compute it yourself with a high-precision calculator.

This value converted to double precision is 5,644,425,081,792,262×2^(-51) and is about 1.83e-16 larger than the exact value of sqrt(2π), which is approximately 5,644,425,081,792,261.587×2^(-51).

### Actual behavior
```c++
static constexpr double sqrt2pi          = 2.50662827463100024161;
```

This value converted to double precision is 5,644,425,081,792,261×2^(-51) and is  2.61e-16 smaller than the exact value of sqrt(2π).  This difference is worse than the difference for the expected behavior.

### Reproducibility

100%

### Versions
Current master branch March 11, 2021.

**Comment by dzenanz** [comment]
How did you discover this?

**Comment by Leengit** [comment]
I discovered that R would give me these mathematical values to arbitrary precision so I thought to try 50 digits of precision and zero tolerance for error in the `TEST_CONSTANT` macro of the ITK version of the `test_math.cxx` file.  Despite that some of the constants were not correctly represented as decimals in `vnl_math.h`, only `sqrt2pi` failed the newly stringent test.  (The other "wrong" decimal values nonetheless gave the same double-precision value as the correct decimal values.)

**Comment by dzenanz** [comment]
I think this can now be closed.
