### ISSUE TITLE
time to drop TravisCI?

### ISSUE THREAD

**Issue by decrispell** [vxl/vxl#855]
We exceeded our TravisCI monthly compute budget , so CI tests are once again no longer running on VXL pull requests.  I'd like to give CircleCI a shot - It appears to have more generous compute allowances for open source projects, and we use it internally at VSI. 

Could a vxl "owner" please bestow me with admin permissions needed to set this up?

**Comment by hjmjohnson** [comment]
@bradking   Could you please pass this information along?

**Comment by bradking** [comment]
I see CircleCI integration for this org is approved.  What else is needed?

**Comment by decrispell** [comment]
Admin permissions are needed to set up CI on a repository, even if CircleCI integration for the organization is already approved.  From the CircleCI interface, I see this:
![image](https://user-images.githubusercontent.com/1390275/132759955-14830e6e-421f-4a6d-841d-c0d0eaaa5cb2.png)

where the "set up project" button should be.

**Comment by bradking** [comment]
@decrispell I added you as an admin.

**Comment by decrispell** [comment]
Thanks @bradking !  I turned on CircleCI builds for all commits on the master branch and all pull requests.
- The contrib libraries are being built, not just core.  If that becomes to onerous we can change to just core.
-  I didn't see any harm in leaving travis enabled, at least for now until we're happy with circleci.
