### ISSUE TITLE
COMP:  Warning about array bound overrrun.

### ISSUE THREAD

**Issue by hjmjohnson** [vxl/vxl#91]
In file included from /scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.txx:13:
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:101:7: warning: array index 2 is past the end of the array (which contains 2 elements) [-Warray-bounds]
      min_[2] <= z && z <= max_[2];
      ^    ~
/scratch/johnsonhj/src/vxl/core/vbl/Templates/vbl_bounding_box+double.2-.cxx:3:1: note: in instantiation of member function 'vbl_bounding_box_base<double,
      vbl_bounding_box_DIM<2> >::inside' requested here
VBL_BOUNDING_BOX_INSTANTIATE(double,2);
^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.txx:42:16: note: expanded from macro 'VBL_BOUNDING_BOX_INSTANTIATE'
template class vbl_bounding_box_base<T , vbl_bounding_box_DIM< DIM > >; \
               ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:162:3: note: array 'min_' declared here
  T min_[DIM_::value];
  ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:101:28: warning: array index 2 is past the end of the array (which contains 2 elements) [-Warray-bounds]
      min_[2] <= z && z <= max_[2];
                           ^    ~
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:163:3: note: array 'max_' declared here
  T max_[DIM_::value];
  ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:134:67: warning: array index 2 is past the end of the array (which contains 2 elements) [-Warray-bounds]
  inline T const& zmin() const { assert(DIM_::value >= 3); return min_[2]; }
                                                                  ^    ~
/scratch/johnsonhj/src/vxl/core/vbl/Templates/vbl_bounding_box+double.2-.cxx:3:1: note: in instantiation of member function 'vbl_bounding_box_base<double,
      vbl_bounding_box_DIM<2> >::zmin' requested here
VBL_BOUNDING_BOX_INSTANTIATE(double,2);
^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.txx:42:16: note: expanded from macro 'VBL_BOUNDING_BOX_INSTANTIATE'
template class vbl_bounding_box_base<T , vbl_bounding_box_DIM< DIM > >; \
               ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:162:3: note: array 'min_' declared here
  T min_[DIM_::value];
  ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:135:67: warning: array index 2 is past the end of the array (which contains 2 elements) [-Warray-bounds]
  inline T const& zmax() const { assert(DIM_::value >= 3); return max_[2]; }
                                                                  ^    ~
/scratch/johnsonhj/src/vxl/core/vbl/Templates/vbl_bounding_box+double.2-.cxx:3:1: note: in instantiation of member function 'vbl_bounding_box_base<double,
      vbl_bounding_box_DIM<2> >::zmax' requested here
VBL_BOUNDING_BOX_INSTANTIATE(double,2);
^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.txx:42:16: note: expanded from macro 'VBL_BOUNDING_BOX_INSTANTIATE'
template class vbl_bounding_box_base<T , vbl_bounding_box_DIM< DIM > >; \
               ^
/scratch/johnsonhj/src/vxl/core/vbl/vbl_bounding_box.h:163:3: note: array 'max_' declared here
  T max_[DIM_::value];
  ^

**Comment by hjmjohnson** [comment]
@thewtex Matt,  Would you be able to fix this warning in VXL?   

If asserts are disabled (i.e. not in debug mode) this seems like a real error.

**Comment by thewtex** [comment]
@hjmjohnson What compiler and flags are required to reproduce the warning?

**Comment by hjmjohnson** [comment]
Just clang (10.10 mac default Xcode 7) with cmake Debug build.  Nothing special.

Hans

**Comment by hjmjohnson** [comment]
resolved with constexpr in C++11.
